function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 12-Apr-2024 21:43:57

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Relative Expected Revenue','Marker','o');
set(plot1(2),'DisplayName','SLF with Extra Seats','Marker','^');
set(plot1(3),'DisplayName','SLF without Extra Seats','Marker','square');

% Create ylabel
ylabel('Percentage');

% Create xlabel
xlabel('Demand');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1.3 1.3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[49.103395 113.03]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XTick',[-1 -0.5 0 0.5 1],'XTickLabel',{'Strong,a0=-1','','','','Weak,a0=1'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');
f = gcf;
saveas(f,'Fig5','epsc');
